# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Build and Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd hackaton/react-split-mini-app
            git pull
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 22
            yarn
            yarn build
            rm -rf /var/www/tagwaiter.ru/dist/
            mv dist/ /var/www/tagwaiter.ru/
            systemctl restart nginx
      
permissions:
  contents: write
